### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by darrell2150** [Cat5TV/pinecraft#100]
Following the instructions these are the results I receive 

paper + installed properly & works
fabric + installed properly & works
forge -  Forge appears to have installed, but is not initializing correctly. It is unlikely to work until this is resolved.
spigot - ls: cannot access '/home/user/minecraft/src/spigot-*.jar': No such file or directory.     Sadly, it appears compiling failed. 
vanilla -  Forge appears to have installed, but is not initializing correctly. It is unlikely to work until this is resolved.

Hardware is Raspberry Pi 4B 4GB
OS Raspberry Pi OS Lite 64 Bit   3/15/24

**Comment by saeckl** [comment]
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-21-jdk

spigot is working

**Comment by darrell2150** [comment]
This is what i get now.

![1](https://github.com/Cat5TV/pinecraft/assets/77147404/65152000-1ce6-42b2-9d89-fb17d49d6509)
![2](https://github.com/Cat5TV/pinecraft/assets/77147404/28dde69e-e52e-4261-b4d7-828c0bc504e1)

**Comment by Arcanum7567** [comment]
Sorry, Fabric is what was giving those issues, not spigot

**Comment by Cat5TV** [comment]
Please make sure you download PinecraftOS as per the README. Pinecraft 4.0 includes Minecraft 1.20.6, which requires Java 21, which is not available in any release of Ubuntu, Debian or Raspberry Pi OS... so I created a base distro specifically for Pinecraft, which is freely available to download. This will solve the issue you are reporting.
