### ISSUE TITLE
the server won't run

### ISSUE THREAD

**Issue by lbap123** [Cat5TV/pinecraft#101]
I try to use the "~/minecraft/server" witch says it will start the server and i did reboot after installing the server and i waited but when i check "htop" and even "/etc/init.d/pinecraft status" it says 0. i tried the 32 bit lite on a raspberry pi 5 and 64 bit lite multpile time and it just does not turn on the server. i turned on the setting after reboot server will turn on and does not work

**Comment by lbap123** [comment]
![Screenshot 2024-05-31 102929](https://github.com/Cat5TV/pinecraft/assets/171356572/f65c8b93-7344-4ee1-b4e7-0e9b7dc7bf08)
this error pops up for vanilla and paper when i try to install it

**Comment by lbap123** [comment]
![Screenshot 2024-05-31 104146](https://github.com/Cat5TV/pinecraft/assets/171356572/4a251b25-a479-43c4-8b63-6f817e3c70cd)

**Comment by Cat5TV** [comment]
Please make sure you download PinecraftOS as per the README. Pinecraft 4.0 includes Minecraft 1.20.6, which requires Java 21, which is not available in any release of Ubuntu, Debian or Raspberry Pi OS... so I created a base distro specifically for Pinecraft, which is freely available to download. This will solve the issue you are reporting.
