### ISSUE TITLE
Pinecraft OS

### ISSUE THREAD

**Issue by Arcanum7567** [Cat5TV/pinecraft#102]
Pinecraft OS refuses to install, can't find a tutorial anywhere to install it but I think something may be wrong.

**Comment by Cat5TV** [comment]
You've provided absolutely ZERO information. Follow the guide in the README and report back with your experience if you have trouble.

**Comment by Arcanum7567** [comment]
Sorry for the lack of detail, after updating to 1.20.6 of course it no
longer works because Java 21 is not available. I understand that. I’ve
downloaded Pinecraft OS, but now what do I open it with? I don’t have
anywhere to input the default login and have that be my devices default OS.
I already have the server installed, just trying to have it not crash post
1.20.6 update.

Thanks, Hayden Cash

**Comment by Cat5TV** [comment]
You need to download the img and flash it just like any other Raspberry Pi image.
