### ISSUE TITLE
Feature Request: Aikar Flags

### ISSUE THREAD

**Issue by eyoung100** [Cat5TV/pinecraft#12]
Being that the Pi 4 and the Rock64 are small footprint, and meant to be energy efficient, it may help to increase Java's efficiency also by adding the flags discussed in [Tuning the JVM – G1GC Garbage Collector Flags for Minecraft](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/), which will not only help Minecraft, but hopefully the Pi itself

This was also discussed in issue #10

**Comment by Michael-BJ-CN** [comment]
It's a good idea to improve the performance. But how much improvement can we get from this? Using SSD to replace sdCard, pre-generating world with the plug-in will be more useful for break the bottle nake.

**Comment by eyoung100** [comment]
> It's a good idea to improve the performance. But how much improvement can we get from this? Using SSD to replace sdCard, pre-generating world with the plug-in will be more effective for break[ing] the bottle[neck].

Those flags aren't meant to break a bottleneck.  A bottleneck is caused by CPU usage.  [Garbage Collection](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)) attempts to optimize RAM usage by scanning for and returning unused RAM back to it's parent process or the system as a whole, so that it can be allocated again, and the cycle repeats.  JAVA is a garbage collected language, because it was built to be OS independent, along with the ability to run on embedded devices with little to no RAM, and perform repetitive tasks efficiently(a.k.a looping).  The Pi meets 2/3 of those criteria (an embedded device with little to no RAM).  Constantly recycling RAM will increase performance, because the amount of RAM is set.  A program can't request more than 8 because there is only 8, but if the 8 is constantly recycled then a program (Minecraft in this case) can constantly request the recycled bits

**Comment by Cat5TV** [comment]
Done. Thanks!
https://github.com/Cat5TV/pinecraft/commit/d9919c743eb41d3ef6046021a50da34c2ae939b6
