### ISSUE TITLE
Feature Request: Tmux support 

### ISSUE THREAD

**Issue by the0remora** [Cat5TV/pinecraft#13]
I Know I am a minority here but would you consider adding Tmux as an alternative to Screen? I have no problem with screen being the default I just prefer tmux and unfortunately don't know how to add this feature myself. 

Thanks

**Comment by Cat5TV** [comment]
Hi @the0remora - while I'd love to help with this, I can't be all things to all people. My focus is on Pinecraft and the future of the product and making Minecraft Server installation easier. Down the line the hope is to implement a web-based interface as per the Patreon goals. If that's of interest to you, I'd encourage you to consider supporting the project's development via https://patreon.com/Pinecraft - but sadly tmux is not part of the plan.

**Comment by the0remora** [comment]
Thanks anyway, I was expecting a no but figured I can't hurt to ask.

I was unaware of the patron, I found this project from the Novaspirit Tech video. Will be adding that to my list.
