### ISSUE TITLE
Choosing Specific Version

### ISSUE THREAD

**Issue by Kastilo** [Cat5TV/pinecraft#15]
Hello!

Is there any way to specifically install a version such as 1.12.2 forge?

**Comment by Cat5TV** [comment]
It is planned. But for now you'd just have to select one of the level seeds that use the version you want. In future, you'll be able to select the Minecraft Server version (2.9 introduces the preliminary code to allow this in a future release). Selecting a seed automatically installs the version that the seed is created on, so it's a hacky but viable way. Just modify the level-seed in your server.properties and re-start your Pinecraft server if you want to use your own seed later.
