### ISSUE TITLE
Cannot run plugins on new Pinecraft version

### ISSUE THREAD

**Issue by jjosephliu** [Cat5TV/pinecraft#16]
Hello, I've configured Pinecraft to Paper server so that I can run plugins on it.
But when I go into the "/mincecraft" folder, there's no "/minecraft/plugins" folder.
I tried creating a folder and putting the plugins in it, but it didn't seem to work.

I used to have a 1.16.5 paper server (pinecraft 2.8 I believe?) that worked with a bunch of plugins, but now that I try it on 1.16.5, (pinecraft 2.9) it doesnt work.

Sorry If I was unclear, I'm not so good at english

**Comment by Cat5TV** [comment]
Hi @jjosephliu --- first, can you please confirm that what you mean is `~/minecraft` and not `/minecraft`? That's a completely different thing, and the correct location is `~/minecraft`

**Comment by jjosephliu** [comment]
> Hi @jjosephliu --- first, can you please confirm that what you mean is `~/minecraft` and not `/minecraft`? That's a completely different thing, and the correct location is `~/minecraft`

Hello, I mean /home/ubuntu/minecraft

**Comment by jjosephliu** [comment]
I still couldn't find the plugins folder as I had before.
Before, it was in /home/ubuntu/minecraft/plugins.
Now when i go to /home/ubuntu/minecraft, there is no plugins folder.

**Comment by Mainnia** [comment]
Im having this issue also

**Comment by jjosephliu** [comment]
Sorry I am an idiot I installed Fabric instead of Paper.
Be sure to install the correct version of minecraft.

I think the first option used to be Paper that's why I just skimmed through it

![image](https://user-images.githubusercontent.com/49181542/124890047-7f5aba80-df8c-11eb-8821-f68513b49c93.png)
