### ISSUE TITLE
need help with plugins

### ISSUE THREAD

**Issue by Mainnia** [Cat5TV/pinecraft#18]
no plugin folder i created one with paper server installed and it wont work can you pls fix this?

**Comment by Mainnia** [comment]
im in ~mincraft now and there is no folder

**Comment by jjosephliu** [comment]
Make sure you're Installing PAPER, not FABRIC

![image](https://user-images.githubusercontent.com/49181542/125000236-cc7a7300-e004-11eb-8739-a7509ba37070.png)

**Comment by Mainnia** [comment]
Ok so I had it wrong his video confused me a little bit
