### ISSUE TITLE
Changing Render Distance

### ISSUE THREAD

**Issue by Joshmandi** [Cat5TV/pinecraft#23]
I’m unable to locate the option to change server render distance on the Pinecraft server. Any guidance with this would be amazing, thank you.

**Comment by ultimatehecker** [comment]
If you do `sudo nano server.properties` in the server folder, then you can access all the properties of the server

**Comment by Cat5TV** [comment]
> If you do `sudo nano server.properties` in the server folder, then you can access all the properties of the server

You should not use `sudo` in this example. Minecraft is installed as the user, not root. Please standby for the tutorial video which is coming very soon.

**Comment by Cat5TV** [comment]
The video to answer this question is here!

https://www.youtube.com/watch?v=4YgS5M4t_Qg
