### ISSUE TITLE
Forge - Not Running - 21.04 Headless Ubuntu

### ISSUE THREAD

**Issue by NodeNextOfficial** [Cat5TV/pinecraft#33]
Same issue as #29.
- Running Base OS
- Followed Cat5TV Videos
- Raspberry pi 4 (8gb)

**Comment by Cat5TV** [comment]
I believe this has been fixed with the release of Pinecraft Installer 3.1. The Forge developers made changes to their own installer which broke the integration with Pinecraft Installer. I've since re-engineered the installer and integrated the changes.
