### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by ThEnchanted** [Cat5TV/pinecraft#34]
Hi! I'm having this idea for a pretty long time, some plugins allow lower loading by preload chunks and I'm having an idea is it possible to do it on Raspberry Pi?
P.S I saw some users doing overclocking GPU on raspberry pi

**Comment by ThEnchanted** [comment]
One of those that I fast can remember is a "chunky"
I'm gonna try to find more

**Comment by Cat5TV** [comment]
Going to close this since not enough info was provided.
