### ISSUE TITLE
Can only install 1.16.5

### ISSUE THREAD

**Issue by Mikaasje** [Cat5TV/pinecraft#35]
Hello. My raspberry pi recently got it’s os corrupted. I run Manjaro XFCE ARM, and was able to recover the files from my Minecraft server. I’ve re-installed XFCE now, put the minecraft folder where it belongs again, and wanted to re-install pinecraft. I have jre 17 installed, but still only get version 1.16.5 as a server install option.(?) It seems the installer can only install Java 8. My previous server ram without problems on 1.17.1. Any way to fix this?

**Comment by Cat5TV** [comment]
Please use the officially supported Base OS. Manjaro is not supported, and specifically XFCE (or any DE for that matter) are unsupported.
