### ISSUE TITLE
Updating manually my paper server

### ISSUE THREAD

**Issue by Cybuuur** [Cat5TV/pinecraft#36]
Hi, I currently need to update the paper jar file on my minecraft server (of course running Pinecraft) and I was wondering if this can be done manually by simply replacing it with the new one. I'm thinking of doing it since Pinecraft installed a paper jar file that is 236 versions behind the current one.
If I'm missing any way of updating it with the installer, please let me know, otherwise can I replace it safely without causing any damage to my server and world?

**Comment by ultimatehecker** [comment]
There is a way of doing this, in your home folder do `sudo wget ` and then copy the link if the download and put it after the wget. Then you will have to remove the other one simply by doing `rm -r {file-name}`. Then you can move the file into the folder by doing `mv {file-name} {ending-location}. As long as the file is the same version as the other it should boot correctly.

**Comment by Cat5TV** [comment]
You need to do a git pull to get the current version of Pinecraft, and then install using the upgrade option. https://www.youtube.com/watch?v=KsmluOmOq54 (while the video shows 1.17 of course that's just the version it was at the time of the video. Same instructions are for 1.18.1 or future releases.)

**Comment by PGQT** [comment]
@Cat5TV Is Robbie OK? its been a long time since ive seen any pinecraft installer updates, and i've not seen any youtube video's in a long time either... I hope you are good, man, we appreciate all you do!
