### ISSUE TITLE
Incorrect version of Vanilla

### ISSUE THREAD

**Issue by Klaohoo** [Cat5TV/pinecraft#4]
Line 160 in install should be updated to reflect the latest server version. The readme states the installer should be downloading 1.17 for Vanilla, but is currently downloading 1.16.5. 

`vanilla="https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar"`

Should be: 

`vanilla="https://launcher.mojang.com/v1/objects/0a269b5f2c5b93b1712d0f5dc43b6182b9ab254e/server.jar"`

Thanks.

**Comment by Cat5TV** [comment]
Thanks for catching that! Fixed.
