### ISSUE TITLE
Autoplugin support (autoplug)

### ISSUE THREAD

**Issue by ThEnchanted** [Cat5TV/pinecraft#41]
Could you add support to Auto plug support, it's had a native web interface to control the server with it and auto-update plugins and server jar update?

**Comment by Cat5TV** [comment]
While I like the idea, I don't like the fact that it requires a 3rd party service. I would prefer to keep my interface focus on PSI. Learn more here: https://www.patreon.com/pinecraft (under Goals, View all, "A web-based interface for Pinecraft...")
