### ISSUE TITLE
CAnt install Java 16

### ISSUE THREAD

**Issue by Wickstroem** [Cat5TV/pinecraft#42]
I've jusrt run the installer twice - can't get it to install java 16...

I've got a Raspberry Pi 4, 8GB.

I ran the Raspberry Pi Imager on my PC, to install the latest Ubuntu Server: 21.10 64-bit. Followed your instructions on your video- to the letter...

When it installs JAva it says: "Trying to install Java 16..." then "Trying to install Java 14..." then "Trying to install Java 13..."....
It finally installs java 8!!

Why won't it install Java 16?

**Comment by eyoung100** [comment]
The easiest way to fix this (workaround) is to install Java before running the PineCraft script.  See a list like: [JDK Distributions](https://sdkman.io/jdks). Make sure you choose a kit that supports arm64.  Note that Java 8 is the default version on Ubuntu 21.04. See [How to Install Java on Ubuntu 21.04](https://fosslover.com/install-java-on-ubuntu/)

**Comment by Cat5TV** [comment]
Try with Pinecraft Installer 3.1+ and see if it helps you out. Java was moved to JRE 17 which is supported on Ubuntu Server 21.10.
