### ISSUE TITLE
Installation says "You don't have enough available ram" but I have a Pi 4 with 4GB

### ISSUE THREAD

**Issue by Renthner** [Cat5TV/pinecraft#43]
Hey there,

I have this problem, when I install Pinecraft, after Java is installed and I chose Spigot as Version, I get this error:

`You don't have enough available ram`

It says I only have about 1.7GB of RAM available, but I have a fresh, new installed Ubuntu Server 21.04 on a Pi 4 with 4GB of RAM, so there should be available way more RAM... Does anybody know how to fix this?

Thanks and Greetings

**Comment by Cat5TV** [comment]
Make sure you don't have any other apps running. Reboot the server before running Pinecraft Installer if in doubt. You won't get the full 4GB since some will be needed for overhead and the OS.
