### ISSUE TITLE
No 1.18

### ISSUE THREAD

**Issue by JOHANnessSKCZ** [Cat5TV/pinecraft#44]
Hello, I wanted to create a minecraft server but when i was creating server in selector there was 1.16.5 but no 1.18.

Please help i need it.
Johan

**Comment by Cat5TV** [comment]
You're not using a supported Base OS. Please see the README under "Base OS" and install the correct one per the link prior to trying to use Pinecraft Installer (otherwise you are limited to what your OS supports, which as you say is only 1.16.5).
