### ISSUE TITLE
Only works on 1.16.5

### ISSUE THREAD

**Issue by DustyCool111** [Cat5TV/pinecraft#45]
Hi there! I am using Rabian to install this and for some reason, it only installs 1.16.5. I would love to know a fix to this. Thanks!
![image](https://user-images.githubusercontent.com/89761788/146495398-0b88a461-41d1-4fb1-8986-6c182dacc699.png)

**Comment by Cat5TV** [comment]
Please read the README. The OS you are using doesn't support 1.18.1. Please install the correct Base OS as per the docs.
