### ISSUE TITLE
ubuntu doesn't boot

### ISSUE THREAD

**Issue by Fanciermot8** [Cat5TV/pinecraft#47]
I cant run ubuntu on my raspberry pi, it doesn't boot and it says no signal on my screen 

any way to fix this, or a different base OS

**Comment by denvercoder** [comment]
Where did you get the OS from?

If you use the link in the Readme then you have to SSH into it because it's a server version.

I use a program called https://www.emtec.com/zoc/ 

To SSH into my server.

Have you watched the new "How To" video?

https://www.youtube.com/watch?v=KsmluOmOq54

**Comment by Fanciermot8** [comment]
I have a Raspberry pi 4, and i used the one in README, when i run a ip scanner for the ip it doesn't come up how would i know that the ubuntu is active

**Comment by denvercoder** [comment]
Can you login to your router and look at the device list? Are you connecting to the Pi through Wifi or Cable?

**Comment by Fanciermot8** [comment]
I'm on cable but no changes on the device list

**Comment by denvercoder** [comment]
Just to check, you used the Raspberry Pi Imager to create a bootable image onto the sdcard?

https://www.raspberrypi.com/software/

**Comment by Fanciermot8** [comment]
Yes i think it was version 1.6.1 that i used

**Comment by denvercoder** [comment]
Mabye the best thing to do is just start over from scratch.

**Comment by Fanciermot8** [comment]
i can run and boot the regular raspberry pi os but ubuntu just doesnt seem to wanna even boot, any other Base OS that could work?

**Comment by Fanciermot8** [comment]
i was able to get the 1.18.1 servers using the latest version of raspberry pi OS
https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/
