### ISSUE TITLE
Manually updating paper 1.16.5

### ISSUE THREAD

**Issue by Sm982** [Cat5TV/pinecraft#48]
I've downloaded Pinecraft and have installed it correctly, how am I able to update Paper 1.16.5 manually to support the latest update which is Paper 1.18.1 ... Would appreciate the help! Thanks!

**Comment by Cat5TV** [comment]
https://www.youtube.com/watch?v=KsmluOmOq54 - while the video shows 1.17 that's just because it's a bit older, but the process is exactly the same.
Just be sure, as ever, that you are running the supported base OS per the README before you even attempt to install or upgrade Pinecraft.
