### ISSUE TITLE
Vanilla and fabric 1.17: 'appears to be installed, but is not initializing properly'

### ISSUE THREAD

**Issue by Isntitethan** [Cat5TV/pinecraft#5]
When I try and install vanilla or fabric servers (1.17) I get the warning:
'Vanilla (or fabric depending on what I'm installing) appears to have installed, but is not initializing properly. It is unlikely to work untill this is resolved'

I am using ubuntu server 21.04 64bit on a raspberry pi 4 b with a 64gig SD card. I saw on the discord someone else had the same problem but it wasn't solved. Someone who was helping me through the whole installation thinks it is to do with the code.

I have no clue what to do about it, so any help is appreciated

**Comment by juliohmb** [comment]
@Isntitethan I've had the same problem on my machine, but with forge for 1.16.5. I fixed it just by downgrading my java version from openjdk-16-jre-headless to openjdk-8-jre-headless, but I think it will not work for you becouse you are trying to run in 1.17. I'd recomend to try to run "~/mincraft/server" script and try to handdle the error, or send it here so then we can help you.
