### ISSUE TITLE
Fabric Mods Not Working

### ISSUE THREAD

**Issue by Flugzeugmann** [Cat5TV/pinecraft#51]
I've installed Paper using Pinecraft, and created a folder titled mods in ~/minecraft, and have put the Fabric API and the Fabric mods of my choice into the folder, and restarted the server. After the server was initiated, I joined the world, but the mods hadn't taken effect.

Am I doing something wrong, or is it the software's fault?

Thanks!

**Comment by Cat5TV** [comment]
You'd need to consult the Fabric community - this is a question for how to use Fabric, not how to use Pinecraft Installer.
