### ISSUE TITLE
not known IP

### ISSUE THREAD

**Issue by persiancatuwu** [Cat5TV/pinecraft#52]
anyone knows how to fix this? 
![image](https://user-images.githubusercontent.com/97259700/148830649-7ddbe526-914b-46d1-a3ba-5819b00b88cb.png)

**Comment by Cat5TV** [comment]
Looks like you've modified your server.properties file manually and misconfigured your server. This is a Minecraft thing. Undo your changes or refer to Minecraft docs. Nothing to do with Pinecraft Installer.
