### ISSUE TITLE
Minecraft's built in commands don't work

### ISSUE THREAD

**Issue by coolpeter98** [Cat5TV/pinecraft#62]
Minecraft's built in commands don't work, i tried in console, gave myself operator but it just says "Unknown Command"

**Comment by Cat5TV** [comment]
Your statement is incorrect. If you are unsure how to issue commands, please watch our tutorial videos such as [this one](https://www.youtube.com/watch?v=1A4FtaiNkrg) or consult Minecraft documentation.
