### ISSUE TITLE
Is there a way to put your own world map?

### ISSUE THREAD

**Issue by malasrdelica** [Cat5TV/pinecraft#64]
I want to put minecraft earth map. so is there a way to put your own world map?

**Comment by Cat5TV** [comment]
This is not an issue. It would have been more appropriate to ask this on our Discord server.

Regardless, the answer was already covered in this tutorial: https://www.youtube.com/watch?v=4YgS5M4t_Qg

See "Moving Minecraft World to Pinecraft Server" 7 minutes in.
