### ISSUE TITLE
update 1.18.2 -> 1.19 

### ISSUE THREAD

**Issue by Rsprintdesign0** [Cat5TV/pinecraft#65]
Hello, first of all thank you for your script, it made the installation of our friends server much easier.

However I contact you that it was impossible for me to migrate to 1.19.
I run the script
I see version 3.3
when choosing between updating or reinstalling
I chose the update, it only offers me 1.18.2 (we are already on 1.18.2)

I would like to understand where I am wrong?

Thank you very much for your work

**Comment by Cat5TV** [comment]
During installation did you choose a level seed that is specific to 1.18.2? That'd be my first guess without knowing more.

**Comment by Cat5TV** [comment]
"I see version 3.3"

User installed an old release rather than current build. 1.19.2 is included in 3.4.
