### ISSUE TITLE
Failure to install on Khadas VIM4

### ISSUE THREAD

**Issue by Guy559** [Cat5TV/pinecraft#66]
First off, thanks for this resource and your YouTube videos. Great stuff and I’m looking forward to making my way through the VIM4/Pinecraft interconnect so that I can host a Minecraft server for my son.

I purchased a new VIM4 with 4GB RAM and 32GB eMMC. I’ve followed the instructions here (and further elaborated on over at Ameridroid) to a tee. However, I keep getting failures in Pinecraft installer after successfully installing the Ubuntu server from Oowow.

I’ve attempted a Paper and Forge install, but both bring up a Warning screen that states: “Paper/Forge appears to have installed, but is not initializing correctly. It is unlikely to work until this is resolved.”

When I check server status, ~/etc/init.d returns a “0”.

If I attempt to manually run ~/Minecraft/server, I receive a “Unsupported Java detected (61.0). Only up to date Java 16 is supported.”  So, not sure if this is a Java install issue?

Any support will be greatly appreciated. Thanks!

**Comment by Cat5TV** [comment]
Sounds like the version of Ubuntu Server you installed may not be supported. Did you first update your OOWOW distro list? If yes, let me know which version it gave you and I'll do some testing locally for you. Since the VIM4 was still under development when I first ported Pinecraft, it's likely some things have changed and need updating, which I'm happy to do. Let me know. Thanks for reporting the issue!

**Comment by Guy559** [comment]
Thanks for the ultra-quick response!

I refreshed and it’s showing the same version i installed: 

Vim4-Ubuntu-20.04-server-linux-5.4-fenix-1.0.11-220620-emmc-develop.raw.img.xz

There’s also a 22.04 dated Jul 21 if that’d be advisable, though I attempted that version first when I received the error… then re-entered oowow to install 20.04 as you recommend.

Seems the vanilla version gives the same Warning screen BUT, when I query via ‘screen’, shows world buying built, etc. However, this wouldn’t work for me as I’d like to use Paper or Forge for the add-ons/mods.

Thanks again! Hoping it’s something simple I did on my end. Great to be back on Linux CLI. Haven’t used very often the last few years.

**Comment by Cat5TV** [comment]
Yes, definitely sounds like a compatibility issue, possibly related to so much work being put into OOWOW and the installed Ubuntu Server. Give me a bit of time to do some further testing... I'll try to replicate your problem this weekend and then patch Pinecraft to resolve it. Cool?

**Comment by Guy559** [comment]
Absolutely! Thanks again for taking the time.

Glad I ran across Ameridroid and Cat5TV. Can already tell this will be a lot of fun to jump in with!

Have a great weekend.

**Comment by Cat5TV** [comment]
You too, thanks.

**Comment by Guy559** [comment]
Noticed v3.4 is now available. Were you able to replicate issues with installing a VIM4 instance and, if so, does this updated version include the updated dependencies?

Oh, related: VIM4 is mentioned as supported h/w but when installing Pinecraft, the screen showing system info calls it 'unknown.' Not sure if this is intentional or not. In your video, this screen correctly displays RPi4B information and confirms overclocking.

 Thanks again for taking a look at this issue.

**Comment by Cat5TV** [comment]
VIM4 [re]testing is under way. Will update you as soon as I have an answer.  :)

**Comment by Cat5TV** [comment]
@Guy559 I installed the supported base OS per the README via Oowow, and immediately cloned and ran the Pinecraft Installer with no issues at all. It initialized my Paper Minecraft server (1.19.2) and I'm able to connect. Performance is exceptional.

Can you re-trace your steps and see where things are getting choked up? I'd like you to try a full reinstall from scratch, following the current Oowow instructions in the Pinecraft README, and let me know if you're still having trouble.

If, at that point, you're still not up and running, I'd like to remote in and take a look for you, see if I can find (and fix) the issue.

The only difference between your setup and mine that I can think of is the fact that you opted for just the 4 GB VIM4. Mine is the 8 GB model. 4 GB should be fine (though not as good as the 8 GB, of course). But perhaps there's something to do with that which I can investigate further with a remote connection.

Cheers!

**Comment by Guy559** [comment]
Okay, let me retrace. I also realized I misspoke: my VIM4 is the 8GB RAM version, not 4GB.

**Comment by Cat5TV** [comment]
Any updates?

**Comment by Guy559** [comment]
Yes, thanks for checking in.

Just re-attempted and the latest version worked fine. Used the exact same steps as before, so suspect it’s as you stated — something to do with dependencies from a previous version combined with latest Oowow update.

Only other thing it could be is that this time, with a clean Ubuntu Server install, I didn’t run sudo apt upgrade immediately following installation. Not sure if that would have tainted the installed JRE version, as the incorrect Java version seemed to be the causal failure during previous attempts.

Really appreciate the support in updating the software. I’ll close this issue. Looking forward to playing around with Pinecraft in the coming week.
