### ISSUE TITLE
Failed to connect to the server

### ISSUE THREAD

**Issue by mrfoxie** [Cat5TV/pinecraft#67]
I have a raspberry pi 4 with 8GB of ram as well as 64bit raspbian os latest version.
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Here is the setup of pinecraft

![image](https://user-images.githubusercontent.com/25217451/184407179-7b210554-1615-4afb-873e-701de22967fe.png)

Its shows online but is unable to connect. Here is the error picture

![image](https://user-images.githubusercontent.com/25217451/184406321-ea9030f3-c837-4bb6-b96f-5daec6984e39.png)

**Comment by Cat5TV** [comment]
GitHub issues are for reporting bugs with the software, not obtaining technical support. Please instead post your question on the Discord server for assistance in how to connect to your Pinecraft Server.

**Comment by mrfoxie** [comment]
can i have discord link
