### ISSUE TITLE
Cant install pinecraft

### ISSUE THREAD

**Issue by DeadGyro** [Cat5TV/pinecraft#68]
Every time I do sudo ./install it keeps saying Installing dialog... Failed. Aborting. Install dialog firs
![Screenshot 2022-08-13 174842](https://user-images.githubusercontent.com/111194198/184503408-728e2764-2272-4da1-b724-2fbe6e3fb1a6.png)

**Comment by Cat5TV** [comment]
You don't appear to be using the supported Base Distro as per the README. Are you sure you installed the correct Base OS first?

**Comment by DeadGyro** [comment]
> You don't appear to be using the supported Base Distro as per the README. Are you sure you installed the correct Base OS first?

Im using the same os you used in your youtube video Ubuntu server 64bit

**Comment by Cat5TV** [comment]
The videos are great for understanding how to install and use Pinecraft, but if you're watching a 2 year old video, you still have to follow the current instructions in the README, otherwise you're using old versions that are not compatible with current Pinecraft Installer.

**Comment by olly1083** [comment]
im having the same isseho on my pi4

**Comment by Cat5TV** [comment]
Just download PinecraftOS and follow the directions.
