### ISSUE TITLE
Spigot update

### ISSUE THREAD

**Issue by Romanoak** [Cat5TV/pinecraft#7]
Tell me if I'm doing this wrong....
spigot 1.17 is out now but pinecraft doesn't update to it. Always 1.16.5 even if I go through the process of updating

thank you

**Comment by Brecht987654321** [comment]
you could change the spigot jar yourself

**Comment by Romanoak** [comment]
@Brecht987654321 I tried that and it broke the server. Not sure if I did it wrong but all I did was switch the 1.16 with the 1.17

**Comment by Brecht987654321** [comment]
@Romanoak you could try renaming the new server jar to the old jar name

**Comment by Romanoak** [comment]
@Brecht987654321 Your suggestion did get me thinking and I found a solution.  You have to go into the server file and change the "1.16.5" to "1.17"
