### ISSUE TITLE
how to upgrade to 1.19.3

### ISSUE THREAD

**Issue by InflictedRhyno** [Cat5TV/pinecraft#74]
hi,
I was looking if i could upgrade to 1.19.3,but didn't find it ..yet :)
did i missed it or isn't it possibible ,yet :)

grtz

**Comment by Cat5TV** [comment]
Please see the upgrade tutorial video I did here: https://www.youtube.com/watch?v=KsmluOmOq54

While that says it's upgrading to 1.7, Pinecraft Installer always upgrades to the latest version as per the README if you follow those steps.
