### ISSUE TITLE
Stopping pinecraft server

### ISSUE THREAD

**Issue by NoahOrta22** [Cat5TV/pinecraft#77]
My Pinecraft server has been "stopping" for over 5 hours.

**Comment by dhry** [comment]
Same thing is happening here. sudo ~\minecraft\reboot just posts a . every 5 seconds and nothing at all happens.

**Comment by Cat5TV** [comment]
And when you connect to the Pinecraft screen sessions and type `stop` what is the output?

**Comment by NoahOrta22** [comment]
It did it the first time but after I turned off the raspberry pi and turned
it back on and did the "stop" it started working.

**Comment by dhry** [comment]
Figured out what this is. I had added "noconsole" to the server shell script to start Paper without a console. This prevented the scripts from being able to pass the stop commands to the console. Removed noconsole from the startup command line and problem fixed.
