### ISSUE TITLE
Installation fails on ODROID-C2

### ISSUE THREAD

**Issue by dhry** [Cat5TV/pinecraft#78]
Trying to install Pinecraft on an ODROID C2 running Ubuntu 20.04.5 LTS. Basically repurposing this older device so I can save one of my RPI4B's.

Git clone obviously works fine.
Sudo install starts up - checks dependencies, trying to install Java 17, then install screen.
Shortly afterward, the screen goes black and basically the cursor flickers at the top left and the lower left of the screen. Nothing is written to the screen at all, just upper left and lower left cursor flickering.
![image](https://user-images.githubusercontent.com/4991066/216861145-b8df141a-3934-4850-b8be-f174bf5f5a1e.png)
https://user-images.githubusercontent.com/4991066/216861362-430aa174-cc2e-44c3-93ef-3922dbfb7668.mp4

I've done apt-get update and upgrade. I also tried this with Ubuntu 18, same thing happens.

What can I try next?

Cheers
DRS

**Comment by Cat5TV** [comment]
Please see the Support Base OS section of the README. https://github.com/Cat5TV/pinecraft#supported-base-os

You need to use 1) a supported operating system and 2) a supported SBC.
