### ISSUE TITLE
Cant update Server (1.19.4)

### ISSUE THREAD

**Issue by MicahRummy** [Cat5TV/pinecraft#79]
When I try to update to 1.19.4 by replacing the .jar files with the new 1.19.4 paper server, it still boots with 1.19.3. replacing in ~/minecraft/libraries/io/papermc/* (all jar files in folders)

**Comment by Cat5TV** [comment]
You need to upgrade to Pinecraft Installer 3.6 and do an upgrade install as per the steps shown in https://www.youtube.com/watch?v=KsmluOmOq54
