### ISSUE TITLE
Paper 1.17 Seed Issue - Pinecraft 2.9

### ISSUE THREAD

**Issue by Michael-BJ-CN** [Cat5TV/pinecraft#8]
Hi, I have used Pinecraft 2.9, chosen Paper 1.17, and input my own seed `-455727652`, but It didn't work. There is no `level-seed=` line in server.properties.

**Comment by Cat5TV** [comment]
Thanks for letting me know. When initializing, servers (such as Paper) a default server.properties file is created. Until now, every one I have ever seen contains the level-seed= line. In Pinecraft Installer, I had taken for granted that it would always exist, and I would therefore find and replace it. While yes, it _should_ exist, it creates a problem if it does not, which you have revealed.

I have, in response, written a patch which will add the missing variables if they do not yet exist in the server.properties file. You're welcome to review the patch [here](https://github.com/Cat5TV/pinecraft/commit/2714c66ec9c0c20853807b09b6e84937981e6f93), but all you have to do is `git pull` and re-run Pinecraft Installer. Should work now.
