### ISSUE TITLE
How do I see the server ip, and make other people able to join

### ISSUE THREAD

**Issue by laziithedev** [Cat5TV/pinecraft#81]
I want to be able to make other people join my server and I don't know the ip it is running on

**Comment by averagenokiauser** [comment]
It's the ip of your Raspberry Pi or other sbc.

**Comment by Cat5TV** [comment]
https://www.youtube.com/watch?v=1A4FtaiNkrg the timestamp is in the pinned comment if you can't watch the whole thing....
