### ISSUE TITLE
Future request 

### ISSUE THREAD

**Issue by jeroentjesgit** [Cat5TV/pinecraft#85]
Hey there I'm loving your work!
Quick request for future releases: would it be possible to add an extra option for creating a superflat world when setting up a server? That would be fantastic!

**Comment by Cat5TV** [comment]
This is done and added to Pinecraft 4.0:

![image](https://github.com/Cat5TV/pinecraft/assets/14219242/75fbbce4-ba59-432b-97c4-84dd85fb9e15)

Enjoy!
