### ISSUE TITLE
Initial Heap size

### ISSUE THREAD

**Issue by jaydenbrooks27** [Cat5TV/pinecraft#88]
Im getting an Initial heap size no matter what size i set it too, any help would be greatly appreciated

**Comment by Nickhoog** [comment]
I get the same error

**Comment by Cat5TV** [comment]
Are you sure you're running the Base Distro as per the README? This would occur if 1) you are running the wrong distro or 2) you have edited ~/minecraft/server - both of which are user error, nothing to do with Pinecraft. Please check the README and confirm you have followed it correctly.
