### ISSUE TITLE
[Suggestion] Previous Minecraft versions

### ISSUE THREAD

**Issue by EliasSauer** [Cat5TV/pinecraft#89]
Please add an option to select previous minecraft versions with paper/fabric/vanilla etc.

I tried manually installing Pinecraft 3.7 via FileZilla so i could install 1.20.1, but the 'install' file did not work.
Or make a new branch for each version, so we can clone older branches.

**Comment by AriTedeschi** [comment]
There is a way to change the installed version
Right after you clone the project, inside "/pinecraft" folder there is an "[install](https://github.com/Cat5TV/pinecraft/blob/main/install#L451)" file which is a shell script (.sh)

You can modify this file to select other versions through the variable $mcver

**Comment by Cat5TV** [comment]
You should be cloning the tag you desire. But in your case, you just forgot to make the install file executable. In Linux, that's `chmod +x install` in the folder you're in, and then run ./install as normal.

Meanwhile, closing this ticket's first thought as a duplicate of https://github.com/Cat5TV/pinecraft/issues/76
