### ISSUE TITLE
unsupported java version

### ISSUE THREAD

**Issue by liloso123** [Cat5TV/pinecraft#90]
hey i just tried to set tthis up on my raspberry pi 4 with papermc and when i try to start the server with the server file i get a message saying that its running a unsupported version of java and dont start the server

**Comment by metl-play** [comment]
Which version of java, do you have installed?
For modern Minecraft, I would recommend using Microsoft (or any other) OpenJDK 17

**Comment by Cat5TV** [comment]
Use the correct Base OS. It's very clear in the README.
