### ISSUE TITLE
Is Pinecraft 3.8 available?

### ISSUE THREAD

**Issue by cqueern** [Cat5TV/pinecraft#98]
I see mentions of 3.8 a couple of times [here](https://github.com/Cat5TV/pinecraft) but the latest on [the release page](https://github.com/Cat5TV/pinecraft/releases) is currently 3.7 I think. Is that expected?

**Comment by Cat5TV** [comment]
At the time you were looking at it, 3.8 would have been current, so not locked to a release (as it was still being updated with each new release of Minecraft 1.20.2. As I write this, Pinecraft's current version is 4.0 (Minecraft 1.20.6) and as always, you get the current version by cloning the main repository (as opposed to visiting the Releases section, which are completed versions - in other words, no more releases will be done for that Minecraft version).
